### ISSUE TITLE
I would also like to ask if you can provide MATLAB code

### ISSUE THREAD

**Issue by chen-april** [RobustFieldAutonomyLab/turtlebot_exploration_3d#12]
Because I am more familiar with using matlab, I want to try to ask if you can find it.

**Comment by baishibona** [comment]
Sorry this was a bit of old code and unfortunately I don’t have matlab
version.
There is GPML in matlab which you might be interested. Good luck!

chen-april <notifications@github.com>于2020年10月23日 周五下午8:04写道：

**Comment by chen-april** [comment]
thank you for your reply
