### ISSUE TITLE
Problem about the code

### ISSUE THREAD

**Issue by babe1031** [RobustFieldAutonomyLab/turtlebot_exploration_3d#3]
Hello, 
  When I write this line of the code on the terminal :  roslaunch turtlebot_exploration_3d minimal_explo.launch 

  I have a problem, there is this displayed :
![screenshot from 2018-06-14 14-11-50](https://user-images.githubusercontent.com/40254204/41387947-bb4ee862-6fdd-11e8-9d5d-993fc18816ab.png)
 
And I don't no why, if anyone could help me, it will be nice

**Comment by baishibona** [comment]
Check if the package setup.bash is imported to your bashes file.

babe1031 <notifications@github.com>于2018年6月13日 周三下午7:19写道：
