### ISSUE TITLE
ROS indigo and kinetic

### ISSUE THREAD

**Issue by dwh635584069** [RobustFieldAutonomyLab/turtlebot_exploration_3d#4]
Hello, could this code run in ROS kinetic? I tried, but failed. what need to be modified if I want to run it in Kinetic? Thank you !

**Comment by varunjammula** [comment]
Installing octomap for kinetic worked for me.

**Comment by baishibona** [comment]
I am glad that it worked out. I thought there may be some capability issues
with eigen library, but looks like it went well.

vjammula <notifications@github.com>于2018年9月24日 周一下午4:26写道：
