### ISSUE TITLE
hi，Can matlab code be published?

### ISSUE THREAD

**Issue by Jimmyzwang-cloud** [RobustFieldAutonomyLab/turtlebot_exploration_3d#6]

**Comment by Jimmyzwang-cloud** [comment]
I read the paper, it feels very interesting, can you post the matlab code?

**Comment by baishibona** [comment]
Hi,
Sorry it’s been a while and I am not sure if I can find the MATLAB code
that is functioning. Is there a specific reason you prefer Matlab when the
c++ is available?



insistlinux <notifications@github.com>于2018年11月9日 周五上午5:40写道：

**Comment by Jimmyzwang-cloud** [comment]
I don't have a turtlebot robot in my hand, I can only simulate it with matlab code. Thank you

**Comment by baishibona** [comment]
Oh, I believe you can install gazebo and run the node in simulation,
however in ROS

insistlinux <notifications@github.com>于2018年11月10日 周六下午7:55写道：

**Comment by Jimmyzwang-cloud** [comment]
Can you leave a contact? For example, WeChat, easy to contact
