### ISSUE TITLE
No map received . Requesting the map...  

### ISSUE THREAD

**Issue by MRwangmaomao** [RobustFieldAutonomyLab/turtlebot_exploration_3d#7]
![2019-03-05 12 22 20](https://user-images.githubusercontent.com/30722103/53780888-5a2f8a80-3f41-11e9-9be6-643f31daeece.png)

**Comment by baishibona** [comment]
seems missing one of the dependencies, did you "sudo apt-get install ros-kinetic-octomap-*"?

**Comment by MRwangmaomao** [comment]
I try the "sudo apt-get install ros-kinetic-octomap-*" . 
Then I chenged the launch file because I use the Kinect2 as the robot's camera.
Now it works OK. 
Thank you very much. This project is a good job.
