### ISSUE TITLE
[ERROR] [1556805462.218564692]: Very few candidates generated, finishing with exploration...

### ISSUE THREAD

**Issue by tianking87** [RobustFieldAutonomyLab/turtlebot_exploration_3d#9]
Hi, I'm running your project, I used Xtion since it don't need the extra battery to drive it.
It showed as follows:
[ WARN] [1556805443.821747525]: Wait for tf: Kinect frame
Writing 0 nodes to output stream...[ WARN] [1556805443.922125934]: Rotate...
Writing 0 nodes to output stream...[ WARN] [1556805446.978718578]: Rotate...
And when it turned around for a circle,it stopped and showed the error as the title.How should I fix this problem?
Thanks in advance.

**Comment by baishibona** [comment]
It seems you don't have depth image going into the exploration node. First check the Xtion sensor data is publishing, second do a remap for the depth topic (you might want to check in the source code to change it if you alway use Xtion sensor.)
